apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "metastore.fullname" . }}
  labels:
    {{- include "metastore.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- range $filename, $file := .Values.configOverrides }}
  {{- $clean := trimPrefix "\n" $file.stringData }}
  {{ $filename }}: |
{{ $clean | indent 4 }}
  {{- end }}

