{{- $hasGCS := and
    (eq .Values.cloud_storage "gcs")
    (eq .Values.gcs.workloadIdentity.enabled false)
-}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "metastore.deploymentName" . }}
  namespace: {{ .Release.Namespace  }}
  labels:
    {{- include "metastore.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "metastore.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- if or .Values.deploymentName .Values.aws.podIamRole }}
      annotations:
      {{- end }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.aws.podIamRole }}
        iam.amazonaws.com/role: {{ .Values.aws.podIamRole }}
      {{- end }}
      labels:
        {{- include "metastore.labels" . | nindent 8 }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{ end }}
      serviceAccountName: {{ include "metastore.serviceAccount" . }}
      containers:
        - name: metastore
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /metastore.sh
          args:
            - hms
          {{- with .Values.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: LOG_LEVEL
              value: "{{ .Values.logLevel }}"
          {{- if eq .Values.cloud_storage "gcs" }}
          # ----------------------------- GCS configuration
          {{- if .Values.gcs.workloadIdentity.enabled }}
            - name: GCS_WORKLOAD_IDENTITY_ENABLED
              value: "true"
          {{- if .Values.gcs.workloadIdentity.gcpServiceAccount }}
            - name: GCS_IMPERSONATION_SERVICE_ACCOUNT
              value: "{{ .Values.gcs.workloadIdentity.gcpServiceAccount }}"
          {{- end }}
          {{- else if .Values.gcs.serviceAccountKeyFile }}
            - name: GCS_SERVICE_ACCOUNT_JSON_KEYFILE
              value: "/var/secrets/google/key.json"
          {{- end }}
          {{- if .Values.gcs.warehouseDirectory }}
            - name: GCS_WAREHOUSE_DIRECTORY
              value: "{{ .Values.gcs.warehouseDirectory }}"
          {{- end }}
          {{- else }}
          # ----------------------------- S3 configuration
          {{- if .Values.s3.url }}
            - name: S3_ENDPOINT
              value: "{{ .Values.s3.url }}"
          {{- end }}
          {{- if .Values.s3.warehouseDirectory }}
            - name: S3_WAREHOUSE_DIRECTORY
              value: "{{ .Values.s3.warehouseDirectory }}"
          {{- end }}
          {{- if .Values.s3.accessKey.secretName }}
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.s3.accessKey.secretName }}
                  key: {{ .Values.s3.accessKey.propertyName }}
          {{- end }}
          {{- if .Values.s3.secretKey.secretName }}
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.s3.secretKey.secretName }}
                  key: {{ .Values.s3.secretKey.propertyName }}
          {{- end }}
          {{- if .Values.s3.proxy }}
            - name: S3_PROXY_HOST
              value: "{{ .Values.s3.proxy.host }}"
            - name: S3_PROXY_PORT
              value: "{{ .Values.s3.proxy.port }}"
          {{- end }}
          {{- if .Values.aws.s3AssumeRoleArn }}
            - name: ASSUME_ROLE_ARN
              value: {{ .Values.aws.s3AssumeRoleArn }}
          {{ end }}
            - name: S3_REQUEST_TIMEOUT
              value: "{{ .Values.s3.requestTimeout }}"
          {{- end }}
          # ----------------------------- DB configuration
            - name: DB_DRIVER_REF
              value: {{ .Values.db.driverRef }}
            - name: DB_DRIVER_NAME
              value: {{ .Values.db.driverName }}
            - name: DB_HOST
              value: {{ .Values.db.host }}
            - name: DB_PORT
              value: "{{ .Values.db.port | default "5432" }}"
            - name: HIVEMS_DB
              value: {{ .Values.db.databaseName }}
            {{- if eq (include "metastore.hasHiveMsUserEnv" .) "false" }}
            - name: HIVEMS_USER
              value: {{ .Values.db.user.name | quote }}
            {{- end }}
            - name: HIVEMS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.user.password.secretName }}
                  key: {{ .Values.db.user.password.propertyName }}
            {{- with .Values.extraEnvRaw }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- if or $hasGCS .Values.configOverrides }}
          volumeMounts:
            {{- if $hasGCS }}
            - name: gcs-key
              mountPath: /var/secrets/google
              readOnly: true
            {{- end }}
            {{- range $filename, $file := .Values.configOverrides }}
            - name: metastore-config
              mountPath: /tmp/envsubst{{ $file.mountPath }}
              subPath: {{ $filename }}
            {{- end }}
          {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- if or $hasGCS .Values.configOverrides }}
      volumes:
        {{- if .Values.configOverrides }}
        - name: metastore-config
          configMap:
            name: {{ include "metastore.fullname" . }}
        {{- end }}
        {{- if $hasGCS }}
        - name: gcs-key
          secret:
            secretName: {{ include "metastore.fullname" . }}-gcs-key
            items:
              - key: hive_metastore_gcs_key
                path: key.json
        {{- end }}
      {{- end }}